### ISSUE TITLE
Removed from AMO

### ISSUE THREAD

**Issue by davidhedlund** [sparhami/fstbh#9]
As pointed out on [reddit](https://www.reddit.com/r/FirefoxAddons/comments/3r8j1x/cant_find_an_addon_can_you_help_me_track_it_down/) Toolbar Autohide have been removed from addons.mozilla.org.

Do you plan to add it back?

We miss it.

**Comment by sparhami** [comment]
Add-ons like Toolbar Autohide will soon no-longer be supported in Firefox, so I don't plan on adding it back. Unfortunately, the new add-ons apis do not support extensions like this.

**Comment by davidhedlund** [comment]
@sparhami I'm sorry to hear that. You did a great job, RIP Toolbar Autohide!
